---
- name: Copy tar.gz to Master node
  copy:
    src: "{{ package_path }}{{ hive_path }}{{ hive_package_name }}"
    dest: "{{ package_path }}{{ hive_path }}"
    mode: 0644

- name: Unarchive hadoop.tar.gz to Master node
  unarchive:
    remote_src: yes
    src: "{{ package_path }}{{ hive_path}}{{ hive_package_name}}"
    dest: /home/hadoop

- name: mv apache-hive-2.3.4-bin to hive
  shell: mv /home/hadoop/apache-hive-2.3.4-bin hive

- name: make related dirs 
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - /home/hadoop/hive/tmp/hive
    - /home/hadoop/hive/warehouse
    - /home/hadoop/hive/auxlib

- name: Copy jdbc to node
  copy:
    src: "{{ package_path }}{{ hive_path }}{{ postgresql_jdbc }}"
    dest: /home/hadoop/hive/auxlib 
    mode: 0755


- name: Template hive.env.sh to nodes
  template:
    src: hive-env.sh.j2
    dest: /home/hadoop/hive/conf/hive-env.sh

- name: Template hive.site.xml to nodes
  template:
    src: hive-site.xml.j2
    dest: /home/hadoop/hive/conf/hive-site.xml
