---
#- name: Copy tar.gz to node
#  copy:
#    src: "{{ package_path }}{{ hbase_path }}{{ hbase_package_name }}"
#    dest: "{{ package_path }}{{ hbase_path }}"
#    mode: 0644
#
#- name: Unarchive hbase.tar.gz to node
#  unarchive:
#    remote_src: yes
#    src: "{{ package_path }}{{ hbase_path}}{{ hbase_package_name}}"
#    dest: /home/hadoop
#
#- name: mv hbase-1.3.3-bin.tar.gz to hbase
#  shell: mv /home/hadoop/hbase-1.3.3 hbase
#
#- name: make related dirs
#  file:
#    path: "{{ item }}"
#    state: directory
#    mode: 0777
#  with_items:
#    - /home/hadoop/hbase/var/hadoop/pids 
#    - /home/hadoop/hbase/logs
#
#- name: Template hbase.env.sh to nodes
#  template:
#    src: hbase-env.sh.j2
#    dest: /home/hadoop/hbase/conf/hbase-env.sh
#
#- name: Template hbase.site.xml to nodes
#  template:
#    src: hbase-site.xml.j2
#    dest: /home/hadoop/hbase/conf/hbase-site.xml
#
- name: Delete regionservers
  file:
    path: "{{ item }}"
    state: absent
    mode: 755
  with_items:
    - /home/hadoop/hbase/conf/regionservers

- name: Template regionservers to nodes
  template:
    src: regionservers.j2
    dest: /home/hadoop/hbase/conf/regionservers

- name: Template backup-masters to nodes
  template:
    src: backup-masters.j2
    dest: /home/hadoop/hbase/conf/backup-masters
