---
#- name: Copy tar.gz to Master node
#  copy:
#    src: "{{ package_path }}{{ hadoop_path }}{{ hadoop_package_name }}"
#    dest: "{{ package_path }}{{ hadoop_path }}"
#    mode: 0644
#
#- name: Unarchive hadoop.tar.gz to Master node
#  unarchive:
#      remote_src: yes
#      src: "{{ package_path }}{{ hadoop_path}}{{ hadoop_package_name}}"
#      dest: /home/hadoop
#
#- name: Rename hadoop dir
#  shell: mv /home/hadoop/hadoop-2.7.3 /home/hadoop/HADOOP_HOME
#  
#- name: Make related dir
#  file:
#    path: "{{ item }}"
#    state: directory    
#    mode: 0755
#  with_items:
#    - /home/hadoop/tmp
#    - /home/hadoop/data/hdfs/namenode
#    - /home/hadoop/data//hdfs/data
#    - /home/hadoop/var/run/hadoop
#    - /home/hadoop/var/log/hadoop
#    - /home/hadoop/data/yarn/local
#    - /home/hadoop/data/yarn/log
#    - /home/hadoop/mr-history/tmp
#    - /home/hadoop/mr-history/done
#    - /home/hadoop/var/lib/hadoop-hdfs/dn_socket
#
- name: Delete core-site.xml,hdfs-site.xml,mapred-site.xml,yarn-site.xml
  file:
    path: "{{ item }}"
    state: absent    
    mode: 755
  with_items:
#    - /home/hadoop/HADOOP_HOME/etc/hadoop/core-site.xml
#    - /home/hadoop/HADOOP_HOME/etc/hadoop/hdfs-site.xml
#    - /home/hadoop/HADOOP_HOME/etc/hadoop/mapred-site.xml
    - /home/hadoop/HADOOP_HOME/etc/hadoop/yarn-site.xml   
#    - /home/hadoop/HADOOP_HOME/etc/hadoop/slaves
#    - /home/hadoop/HADOOP_HOME/etc/hadoop/hadoop-env.sh
#
#- name: Template new core-site.xml files to masters
#  template:
#    src: core-site-master.xml.j2
#    dest: /home/hadoop/HADOOP_HOME/etc/hadoop/core-site.xml
#    mode: 0644
#
#- name: Template new hdfs-site.xml files to masters
#  template:
#    src: hdfs-site-master.xml.j2
#    dest: /home/hadoop/HADOOP_HOME/etc/hadoop/hdfs-site.xml
#    mode: 0644
#
#- name: Template new mapred-site.xml files to masters
#  template:
#    src: mapred-site-master.xml.j2
#    dest: /home/hadoop/HADOOP_HOME/etc/hadoop/mapred-site.xml
#    mode: 0644
#
- name: Template new yarn-site.xml files to masters
  template:
    src: yarn-site-master.xml.j2
    dest: /home/hadoop/HADOOP_HOME/etc/hadoop/yarn-site.xml
    mode: 0644
#
#- name: Template new Slaves files to masters
#  template:
#    src: slaves.j2
#    dest: /home/hadoop/HADOOP_HOME/etc/hadoop/slaves
#    mode: 0644
#
#- name: Template new hadoop_env.sh to Masters
#  template:
#    src: hadoop-env.sh.j2 
#    dest: /home/hadoop/HADOOP_HOME/etc/hadoop/hadoop-env.sh
#    mode: 0644
